prefix = "." # tells MeTA where to search for datasets

dataset = "citeseer" # a subfolder under the prefix directory
corpus = "citeseer.toml" # a configuration file for the corpus specifying its format & additional args

index = "citeseer-idx" # subfolder of the current working directory to place index files

query-judgements = "citeseer/citeseer-qrels.txt" # file containing the relevance judgments for this dataset

stop-words = "lemur-stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
